version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8888:8888
    volumes:
      - ./src:/usr/share/nginx/html
      - ./logs:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
